---
default_language_version:
  python: "python3"
exclude: "^.*\b(migrations)\b.*$"
repos:
  - repo: "https://github.com/adamchainz/django-upgrade"
    rev: "1.16.0"
    hooks:
      - id: "django-upgrade"
        args: ['--target-version', '5.0']
  - repo: "https://github.com/astral-sh/ruff-pre-commit"
    rev: "v0.2.2"
    hooks:
      - id: "ruff"
        args: ["--fix"]
      - id: "ruff-format"
  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: 'v1.1.1'
    hooks:
      - id: "mypy"
        exclude: "src/.*/tests.py"
        additional_dependencies:
          - "django-stubs[compatible-mypy]"
          - "django-stubs-ext"
          - "types-requests"
          - "dealer==2.1.0"
          - "django-allauth==0.61.1"
          - "django-bootstrap5==23.4"
          - "django-cors-headers==4.3.1"
          - "django-guardian==2.4.0"
          - "django-htmx==1.17.3"
          - "django-imagekit==5.0.0"
          - "django-ninja==1.1.0"
          - "django-oauth-toolkit==2.3.0"
          - "django-polymorphic==3.1.0"
          - "django-taggit==5.0.1"
          - "environs[django]==11.0.0"
          - "fontawesomefree==6.5.1"
          - "orjson==3.9.15"
          - "Pillow==10.2.0"
          - "psycopg2-binary==2.9.9"
          - "python-magic==0.4.27"
          - "django-filter==24.2"
          - "django-tables2==2.7.0"
          - "django-debug-toolbar==4.1.0"
...
